-   id: md_code_sync
    name: md_code_sync
    description: ''
    entry:  bash -c 'for x in "$@"; do md_code_sync -i "$x"; done' -- 
    language: python
    types: [markdown]
    args: []
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '0'
