-   id: md_code_sync
    name: md_code_sync
    description: ''
    entry:  bash -c 'md_code_sync -v DEBUG -w "$@"'
    language: python
    types: [markdown]
    args: []
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '0'
