-   id: md_code_sync
    name: md_code_sync
    description: ''
    entry:  md_code_sync
    language: python
    types: [markdown]
    args: ["-v", "ERROR", "-w"]
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '0'
